### ISSUE TITLE
Check over components

### ISSUE THREAD

**Issue by lbuckley** [trenchproject/PhysicalProcessesEcosystems#2]
Tables, eqns, figures, etc.

**Comment by ys634** [comment]
ED195420 -- Calculus-Integration ch.1
ED197985 -- Calculus differentiation ch.2
            figure 7 are lacking 3 figures. Figure A, B in computer exercise and a figure in
            ANSWERS TO THE COMPUTER EXERCISES not present
ED195421 -- Dimensional Methods ch.3
            missing Fig. 7, 8
ED197989 -- physics ch.4
ED195428 -- The First Law of Thermodynamics for Ecosystems ch.5
ED195427 -- Applications of the First Law to Ecological Systems ch.6
ED197991 -- heat transfer ch.7
ED195432 -- Light and sound ch.8
            pages 37, 38, 45, 46 missing
ED195430 -- Cimate space concept ch.9
ED195429 -- Animal Thermoregulation ch.10
ED197986 -- Transpiration and leaf transfer ch.11
ED195431 -- heat balance of a sheep ch.12
            pages 9, 11, 12, 15, 16, 20, 31, 32, 34, 35, 36 missing
ED195433 -- soil heat flow ch.13
ED195436 -- Turbulance and fluid flow ch.14

**Comment by ys634** [comment]
ch.1:
preface is different from the original

ch.2: 
figure 7 are lacking 3 figures. Figure A, B in computer exercise and a figure in ANSWERS TO THE COMPUTER EXERCISES not present

ch.3: 
missing Fig. 7, 8

ch.8:
pages 37, 38, 45, 46 missing

ch.12
pages 9, 11, 12, 15, 16, 20, 31, 32, 34, 35, 36 missing

**Comment by lbuckley** [comment]
Please recreate reference list for module 8.

**Comment by ys634** [comment]
Added references except for 3 that couldn't be found. Might be easier to just omit them from the text.

**Comment by lbuckley** [comment]
OK. Altered references.
