### ISSUE TITLE
Sheep heat transfer (ch.12) missing pages

### ISSUE THREAD

**Issue by ys634** [trenchproject/PhysicalProcessesEcosystems#3]
- [ ] p.4 energy balance (1 page chapter)
can be covered by II. HEAT BALANCE OF THE BODY AND OF THE FLEECE?

- [ ] pp.7, 8, 10 heat transfer by conduction within animal (8-page chapter)

- [ ] p.11 heat loss by convection opening page
can be covered by III. HEAT Loss BY CONVECTION?
An Introduction to Heat Transfer (Fishenden and Saunders, 1950) has more detailed data

- [ ] p.15 heat loss by radiation (1 page chapter)
can be covered by IV. LONG-WAVE RADIATION Loss?

- [ ] pp.26-31 acknowledgements and references

**Comment by lbuckley** [comment]
Missing material filled in. Needs checking.
